In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv('1990_2022_natural_disasters_2.csv')
df.head()

C:\Users\krcon\AppData\Local\Temp\ipykernel_30564\974250801.py:1: DtypeWarning: Columns (24,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv('1990_2022_natural_disasters_2.csv')

,Dis No,Year,Seq,Glide,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Event Name,...,"Reconstruction Costs, Adjusted ('000 US$)",Insured Damages ('000 US$),"Insured Damages, Adjusted ('000 US$)",Total Damages ('000 US$),"Total Damages, Adjusted ('000 US$)",CPI,Adm Level,Admin1 Code,Admin2 Code,Geo Locations
0,1990-9579-CMR,1990,9579,NaN,Natural,Climatological,Drought,Drought,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,48.218797,NaN,NaN,NaN,NaN
1,1990-0230-ECU,1990,230,NaN,Natural,Geophysical,Earthquake,Ground movement,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,48.218797,NaN,NaN,NaN,NaN
2,1990-0361-AUT,1990,361,NaN,Natural,Meteorological,Storm,Convective storm,Severe storm,NaN,...,NaN,28200.0,58483.0,NaN,NaN,48.218797,NaN,NaN,NaN,NaN
3,1990-9059-BOL,1990,9059,NaN,Natural,Climatological,Drought,Drought,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,48.218797,NaN,NaN,NaN,NaN
4,1990-0248-AFG,1990,248,NaN,Natural,Meteorological,Extreme temperature,Cold wave,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,48.218797,NaN,NaN,NaN,NaN

In [3]:
list(df)

['Dis No',
 'Year',
 'Seq',
 'Glide',
 'Disaster Group',
 'Disaster Subgroup',
 'Disaster Type',
 'Disaster Subtype',
 'Disaster Subsubtype',
 'Event Name',
 'Country',
 'ISO',
 'Region',
 'Continent',
 'Location',
 'Origin',
 'Associated Dis',
 'Associated Dis2',
 'OFDA Response',
 'Appeal',
 'Declaration',
 "AID Contribution ('000 US$)",
 'Dis Mag Value',
 'Dis Mag Scale',
 'Latitude',
 'Longitude',
 'Local Time',
 'River Basin',
 'Start Year',
 'Start Month',
 'Start Day',
 'End Year',
 'End Month',
 'End Day',
 'Total Deaths',
 'No Injured',
 'No Affected',
 'No Homeless',
 'Total Affected',
 "Reconstruction Costs ('000 US$)",
 "Reconstruction Costs, Adjusted ('000 US$)",
 "Insured Damages ('000 US$)",
 "Insured Damages, Adjusted ('000 US$)",
 "Total Damages ('000 US$)",
 "Total Damages, Adjusted ('000 US$)",
 'CPI',
 'Adm Level',
 'Admin1 Code',
 'Admin2 Code',
 'Geo Locations']

In [4]:
df = df.drop(columns=["Glide", "Disaster Subsubtype", "ISO", "Origin", "Associated Dis", "Associated Dis2","OFDA Response", "Appeal", "Declaration", "Local Time", "River Basin", "No Injured", "No Affected", "No Homeless", "Adm Level", "Admin1 Code", "Admin2 Code"])
df.head()

,Dis No,Year,Seq,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Event Name,Country,Region,...,Total Deaths,Total Affected,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damages ('000 US$),"Insured Damages, Adjusted ('000 US$)",Total Damages ('000 US$),"Total Damages, Adjusted ('000 US$)",CPI,Geo Locations
0,1990-9579-CMR,1990,9579,Natural,Climatological,Drought,Drought,NaN,Cameroon,Middle Africa,...,NaN,186900.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
1,1990-0230-ECU,1990,230,Natural,Geophysical,Earthquake,Ground movement,NaN,Ecuador,South America,...,4.0,6510.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
2,1990-0361-AUT,1990,361,Natural,Meteorological,Storm,Convective storm,NaN,Austria,Western Europe,...,NaN,NaN,NaN,NaN,28200.0,58483.0,NaN,NaN,48.218797,NaN
3,1990-9059-BOL,1990,9059,Natural,Climatological,Drought,Drought,NaN,Bolivia (Plurinational State of),South America,...,NaN,283160.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
4,1990-0248-AFG,1990,248,Natural,Meteorological,Extreme temperature,Cold wave,NaN,Afghanistan,Southern Asia,...,144.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN

In [5]:
df.columns=df.columns.str.strip().str.lower()
df.columns

Index(['dis no', 'year', 'seq', 'disaster group', 'disaster subgroup',
       'disaster type', 'disaster subtype', 'event name', 'country', 'region',
       'continent', 'location', 'aid contribution ('000 us$)', 'dis mag value',
       'dis mag scale', 'latitude', 'longitude', 'start year', 'start month',
       'start day', 'end year', 'end month', 'end day', 'total deaths',
       'total affected', 'reconstruction costs ('000 us$)',
       'reconstruction costs, adjusted ('000 us$)',
       'insured damages ('000 us$)', 'insured damages, adjusted ('000 us$)',
       'total damages ('000 us$)', 'total damages, adjusted ('000 us$)', 'cpi',
       'geo locations'],
      dtype='object')

In [8]:
df2= df.rename(str.strip, axis ='columns')
df2

,dis no,year,seq,disaster group,disaster subgroup,disaster type,disaster subtype,event name,country,region,...,total deaths,total affected,reconstruction costs ('000 us$),"reconstruction costs, adjusted ('000 us$)",insured damages ('000 us$),"insured damages, adjusted ('000 us$)",total damages ('000 us$),"total damages, adjusted ('000 us$)",cpi,geo locations
0,1990-9579-CMR,1990,9579,Natural,Climatological,Drought,Drought,NaN,Cameroon,Middle Africa,...,NaN,186900.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
1,1990-0230-ECU,1990,230,Natural,Geophysical,Earthquake,Ground movement,NaN,Ecuador,South America,...,4.0,6510.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
2,1990-0361-AUT,1990,361,Natural,Meteorological,Storm,Convective storm,NaN,Austria,Western Europe,...,NaN,NaN,NaN,NaN,28200.0,58483.0,NaN,NaN,48.218797,NaN
3,1990-9059-BOL,1990,9059,Natural,Climatological,Drought,Drought,NaN,Bolivia (Plurinational State of),South America,...,NaN,283160.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
4,1990-0248-AFG,1990,248,Natural,Meteorological,Extreme temperature,Cold wave,NaN,Afghanistan,Southern Asia,...,144.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19839,2022-0255-COD,2022,255,Natural,Biological,Epidemic,Viral disease,Plague,Congo (the Democratic Republic of the),Middle Africa,...,2.0,91738.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ituri (Adm2).
19840,2022-0263-COD,2022,263,Natural,Biological,Epidemic,Viral disease,Ebola Virus Disease,Congo (the Democratic Republic of the),Middle Africa,...,5.0,141.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19841,2022-0164-COD,2022,164,Technological,Technological,Transport accident,Rail,NaN,Congo (the Democratic Republic of the),Middle Africa,...,75.0,125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19842,2022-0216-ZWE,2022,216,Technological,Technological,Transport accident,Road,NaN,Zimbabwe,Eastern Africa,...,35.0,71.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19843,2022-0201-TLS,2022,201,Natural,Biological,Epidemic,Viral disease,Dengue,Timor-Leste,South-Eastern Asia,...,20.0,1353.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df2.columns

Index(['dis no', 'year', 'seq', 'disaster group', 'disaster subgroup',
       'disaster type', 'disaster subtype', 'event name', 'country', 'region',
       'continent', 'location', 'aid contribution ('000 us$)', 'dis mag value',
       'dis mag scale', 'latitude', 'longitude', 'start year', 'start month',
       'start day', 'end year', 'end month', 'end day', 'total deaths',
       'total affected', 'reconstruction costs ('000 us$)',
       'reconstruction costs, adjusted ('000 us$)',
       'insured damages ('000 us$)', 'insured damages, adjusted ('000 us$)',
       'total damages ('000 us$)', 'total damages, adjusted ('000 us$)', 'cpi',
       'geo locations'],
      dtype='object')

In [23]:
df3= df2.drop(2[df2['disaster group'] == 'Technological'].index)

print(df3)

<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
C:\Users\krcon\AppData\Local\Temp\ipykernel_30564\4203924294.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  df3= df2.drop(2[df2['disaster group'] == 'Technological'].index)
C:\Users\krcon\AppData\Local\Temp\ipykernel_30564\4203924294.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  df3= df2.drop(2[df2['disaster group'] == 'Technological'].index)
C:\Users\krcon\AppData\Local\Temp\ipykernel_30564\4203924294.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  df3= df2.drop(2[df2['disaster group'] == 'Technological'].index)
C:\Users\krcon\AppData\Local\Temp\ipykernel_30564\4203924294.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  df3= df2.drop(2[df2['disaster group'] == 'Technological'].index)

TypeError: 'int' object is not subscriptable

In [22]:
df4= df3.drop(df3[df3['disaster group'] == 'Complex Disasters'].index)
print(df4)

              dis no  year   seq disaster group disaster subgroup  \
0      1990-9579-CMR  1990  9579        Natural    Climatological
1      1990-0230-ECU  1990   230        Natural       Geophysical
2      1990-0361-AUT  1990   361        Natural    Meteorological
3      1990-9059-BOL  1990  9059        Natural    Climatological
4      1990-0248-AFG  1990   248        Natural    Meteorological
...              ...   ...   ...            ...               ...
19837  2022-0356-ZAF  2022   356        Natural      Hydrological
19838  2022-0209-COD  2022   209        Natural    Meteorological
19839  2022-0255-COD  2022   255        Natural        Biological
19840  2022-0263-COD  2022   263        Natural        Biological
19843  2022-0201-TLS  2022   201        Natural        Biological

             disaster type  disaster subtype           event name  \
0                  Drought           Drought                  NaN
1               Earthquake   Ground movement                  NaN
2                    Storm  Convective storm                  NaN
3                  Drought           Drought                  NaN
4      Extreme temperature         Cold wave                  NaN
...                    ...               ...                  ...
19837                Flood               NaN                  NaN
19838                Storm  Convective storm                  NaN
19839             Epidemic     Viral disease               Plague
19840             Epidemic     Viral disease  Ebola Virus Disease
19843             Epidemic     Viral disease               Dengue

                                      country              region  ...  \
0                                    Cameroon       Middle Africa  ...
1                                     Ecuador       South America  ...
2                                     Austria      Western Europe  ...
3            Bolivia (Plurinational State of)       South America  ...
4                                 Afghanistan       Southern Asia  ...
...                                       ...                 ...  ...
19837                            South Africa     Southern Africa  ...
19838  Congo (the Democratic Republic of the)       Middle Africa  ...
19839  Congo (the Democratic Republic of the)       Middle Africa  ...
19840  Congo (the Democratic Republic of the)       Middle Africa  ...
19843                             Timor-Leste  South-Eastern Asia  ...

      total deaths total affected  reconstruction costs ('000 us$)  \
0              NaN       186900.0                              NaN
1              4.0         6510.0                              NaN
2              NaN            NaN                              NaN
3              NaN       283160.0                              NaN
4            144.0            NaN                              NaN
...            ...            ...                              ...
19837          NaN          204.0                              NaN
19838         26.0            NaN                              NaN
19839          2.0        91738.0                              NaN
19840          5.0          141.0                              NaN
19843         20.0         1353.0                              NaN

       reconstruction costs, adjusted ('000 us$) insured damages ('000 us$)  \
0                                            NaN                        NaN
1                                            NaN                        NaN
2                                            NaN                    28200.0
3                                            NaN                        NaN
4                                            NaN                        NaN
...                                          ...                        ...
19837                                        NaN                        NaN
19838                                        NaN                        NaN
19839                                        NaN                        NaN
19840                                        NaN                        NaN
19843                                        NaN                        NaN

      insured damages, adjusted ('000 us$) total damages ('000 us$)  \
0                                      NaN                      NaN
1                                      NaN                      NaN
2                                  58483.0                      NaN
3                                      NaN                      NaN
4                                      NaN                      NaN
...                                    ...                      ...
19837                                  NaN                      NaN
19838                                  NaN                      NaN
19839                                  NaN                      NaN
19840                                  NaN                      NaN
19843                                  NaN                      NaN

       total damages, adjusted ('000 us$)        cpi  geo locations
0                                     NaN  48.218797            NaN
1                                     NaN  48.218797            NaN
2                                     NaN  48.218797            NaN
3                                     NaN  48.218797            NaN
4                                     NaN  48.218797            NaN
...                                   ...        ...            ...
19837                                 NaN        NaN            NaN
19838                                 NaN        NaN            NaN
19839                                 NaN        NaN  Ituri (Adm2).
19840                                 NaN        NaN            NaN
19843                                 NaN        NaN            NaN

[12302 rows x 33 columns]

In [25]:
df4.head(50)

,dis no,year,seq,disaster group,disaster subgroup,disaster type,disaster subtype,event name,country,region,...,total deaths,total affected,reconstruction costs ('000 us$),"reconstruction costs, adjusted ('000 us$)",insured damages ('000 us$),"insured damages, adjusted ('000 us$)",total damages ('000 us$),"total damages, adjusted ('000 us$)",cpi,geo locations
0,1990-9579-CMR,1990,9579,Natural,Climatological,Drought,Drought,NaN,Cameroon,Middle Africa,...,NaN,186900.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
1,1990-0230-ECU,1990,230,Natural,Geophysical,Earthquake,Ground movement,NaN,Ecuador,South America,...,4.0,6510.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
2,1990-0361-AUT,1990,361,Natural,Meteorological,Storm,Convective storm,NaN,Austria,Western Europe,...,NaN,NaN,NaN,NaN,28200.0,58483.0,NaN,NaN,48.218797,NaN
3,1990-9059-BOL,1990,9059,Natural,Climatological,Drought,Drought,NaN,Bolivia (Plurinational State of),South America,...,NaN,283160.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
4,1990-0248-AFG,1990,248,Natural,Meteorological,Extreme temperature,Cold wave,NaN,Afghanistan,Southern Asia,...,144.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
11,1990-0638-ARG,1990,638,Natural,Hydrological,Flood,NaN,NaN,Argentina,South America,...,21.0,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
12,1990-0052-ATG,1990,52,Natural,Meteorological,Storm,Tropical cyclone,Gustav,Antigua and Barbuda,Caribbean,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
13,1990-0724-AUS,1990,724,Natural,Hydrological,Flood,Coastal flood,NaN,Australia,Australia and New Zealand,...,6.0,NaN,NaN,NaN,NaN,NaN,78200.0,162177.0,48.218797,NaN
14,1990-0087-AUS,1990,87,Natural,Hydrological,Flood,Riverine flood,NaN,Australia,Australia and New Zealand,...,6.0,6000.0,NaN,NaN,NaN,NaN,195500.0,405444.0,48.218797,NaN
15,1990-0422-AUS,1990,422,Natural,Meteorological,Storm,Tropical cyclone,Joy,Australia,Australia and New Zealand,...,NaN,NaN,NaN,NaN,NaN,NaN,155600.0,322696.0,48.218797,NaN
16,1990-0269-AUS,1990,269,Natural,Climatological,Wildfire,"Land fire (Brush, Bush, Pasture)",NaN,Australia,Australia and New Zealand,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
22,1990-0376-AUT,1990,376,Natural,Meteorological,Storm,Convective storm,NaN,Austria,Western Europe,...,NaN,NaN,NaN,NaN,37700.0,78185.0,NaN,NaN,48.218797,NaN
23,1990-0721-AUT,1990,721,Natural,Meteorological,Storm,NaN,Ottilie and Polly,Austria,Western Europe,...,NaN,NaN,NaN,NaN,NaN,NaN,10000.0,20739.0,48.218797,NaN
24,1990-0722-AUT,1990,722,Natural,Meteorological,Storm,NaN,Vivian,Austria,Western Europe,...,NaN,NaN,NaN,NaN,80000.0,165910.0,120000.0,248866.0,48.218797,NaN
25,1990-0723-AUT,1990,723,Natural,Meteorological,Storm,NaN,Wiebke,Austria,Western Europe,...,3.0,NaN,NaN,NaN,80000.0,165910.0,120000.0,248866.0,48.218797,NaN
27,1990-0717-BEL,1990,717,Natural,Meteorological,Storm,NaN,Daria,Belgium,Western Europe,...,10.0,NaN,NaN,NaN,250000.0,518470.0,350000.0,725858.0,48.218797,NaN
28,1990-0718-BEL,1990,718,Natural,Meteorological,Storm,NaN,Herta,Belgium,Western Europe,...,NaN,NaN,NaN,NaN,120000.0,248866.0,180000.0,373298.0,48.218797,NaN
29,1990-0719-BEL,1990,719,Natural,Meteorological,Storm,NaN,Judith,Belgium,Western Europe,...,NaN,NaN,NaN,NaN,NaN,NaN,60000.0,124433.0,48.218797,NaN
30,1990-0721-BEL,1990,721,Natural,Meteorological,Storm,NaN,Ottilie and Polly,Belgium,Western Europe,...,NaN,NaN,NaN,NaN,30000.0,62216.0,60000.0,124433.0,48.218797,NaN
31,1990-0722-BEL,1990,722,Natural,Meteorological,Storm,NaN,Vivian,Belgium,Western Europe,...,5.0,NaN,NaN,NaN,200000.0,414776.0,240000.0,497731.0,48.218797,NaN
32,1990-0723-BEL,1990,723,Natural,Meteorological,Storm,NaN,Wiebke,Belgium,Western Europe,...,1.0,NaN,NaN,NaN,60000.0,124433.0,90000.0,186649.0,48.218797,NaN
33,1990-9578-BFA,1990,9578,Natural,Climatological,Drought,Drought,NaN,Burkina Faso,Western Africa,...,NaN,2600000.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
34,1990-0090-BGD,1990,90,Natural,Meteorological,Storm,Convective storm,NaN,Bangladesh,Southern Asia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
35,1990-0096-BGD,1990,96,Natural,Meteorological,Storm,Convective storm,NaN,Bangladesh,Southern Asia,...,54.0,40200.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
36,1990-0095-BGD,1990,95,Natural,Hydrological,Flood,Riverine flood,NaN,Bangladesh,Southern Asia,...,166.0,11600.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
37,1990-0609-BGD,1990,609,Natural,Hydrological,Flood,Riverine flood,NaN,Bangladesh,Southern Asia,...,65.0,2000000.0,NaN,NaN,NaN,NaN,6000.0,12443.0,48.218797,NaN
38,1990-0576-BGD,1990,576,Natural,Meteorological,Storm,Tropical cyclone,Ofa,Bangladesh,Southern Asia,...,370.0,13870.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
39,1990-0424-BGD,1990,424,Natural,Meteorological,Extreme temperature,Cold wave,NaN,Bangladesh,Southern Asia,...,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
40,1990-0706-BGD,1990,706,Natural,Meteorological,Extreme temperature,Cold wave,NaN,Bangladesh,Southern Asia,...,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
49,1990-0421-BGD,1990,421,Natural,Meteorological,Storm,NaN,NaN,Bangladesh,Southern Asia,...,250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
50,1990-0020-BGR,1990,20,Natural,Geophysical,Earthquake,Ground movement,NaN,Bulgaria,Eastern Europe,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
52,1990-0042-BHS,1990,42,Natural,Meteorological,Storm,Tropical cyclone,Arthur,Bahamas (the),Caribbean,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
53,1990-0641-BLZ,1990,641,Natural,Meteorological,Extreme temperature,Cold wave,NaN,Belize,Central America,...,NaN,NaN,NaN,NaN,NaN,NaN,2250.0,4666.0,48.218797,NaN
54,1990-0642-BLZ,1990,642,Natural,Hydrological,Flood,NaN,NaN,Belize,Central America,...,NaN,NaN,NaN,NaN,NaN,NaN,2200.0,4563.0,48.218797,NaN
55,1990-0411-BRA,1990,411,Natural,Hydrological,Flood,Flash flood,NaN,Brazil,South America,...,17.0,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
56,1990-0710-BRA,1990,710,Natural,Hydrological,Flood,Riverine flood,NaN,Brazil,South America,...,7.0,800.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
60,1990-9604-BWA,1990,9604,Natural,Climatological,Drought,Drought,NaN,Botswana,Southern Africa,...,NaN,100000.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
61,1990-0644-CAN,1990,644,Natural,Hydrological,Flood,Riverine flood,NaN,Canada,Northern America,...,8.0,NaN,NaN,NaN,NaN,NaN,8500.0,17628.0,48.218797,NaN
64,1990-0389-CHE,1990,389,Natural,Meteorological,Storm,NaN,NaN,Switzerland,Western Europe,...,NaN,NaN,NaN,NaN,77800.0,161348.0,NaN,NaN,48.218797,NaN
65,1990-0721-CHE,1990,721,Natural,Meteorological,Storm,NaN,Ottilie and Polly,Switzerland,Western Europe,...,3.0,NaN,NaN,NaN,NaN,NaN,100000.0,207388.0,48.218797,NaN
66,1990-0722-CHE,1990,722,Natural,Meteorological,Storm,NaN,Vivian,Switzerland,Western Europe,...,1.0,NaN,NaN,NaN,60000.0,124433.0,90000.0,186649.0,48.218797,NaN
67,1990-0723-CHE,1990,723,Natural,Meteorological,Storm,NaN,Wiebke,Switzerland,Western Europe,...,1.0,NaN,NaN,NaN,60000.0,124433.0,90000.0,186649.0,48.218797,NaN
69,1990-0639-CHL,1990,639,Natural,Hydrological,Flood,NaN,NaN,Chile,South America,...,NaN,2500.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
70,1990-0716-CHN,1990,716,Natural,Meteorological,Storm,Convective storm,NaN,China,Eastern Asia,...,33.0,NaN,NaN,NaN,NaN,NaN,210000.0,435515.0,48.218797,NaN
71,1990-0252-CHN,1990,252,Natural,Meteorological,Storm,Convective storm,NaN,China,Eastern Asia,...,25.0,NaN,NaN,NaN,NaN,NaN,335.0,695.0,48.218797,NaN
72,1990-0698-CHN,1990,698,Natural,Meteorological,Storm,Convective storm,NaN,China,Eastern Asia,...,2.0,550.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
73,1990-0093-CHN,1990,93,Natural,Geophysical,Earthquake,Ground movement,NaN,China,Eastern Asia,...,1.0,30016.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
74,1990-0099-CHN,1990,99,Natural,Geophysical,Earthquake,Ground movement,NaN,China,Eastern Asia,...,126.0,34319.0,NaN,NaN,NaN,NaN,58350.0,121011.0,48.218797,NaN
75,1990-0036-CHN,1990,36,Natural,Geophysical,Mass movement (dry),Landslide,NaN,China,Eastern Asia,...,69.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN
76,1990-0284-CHN,1990,284,Natural,Geophysical,Mass movement (dry),Landslide,NaN,China,Eastern Asia,...,4.0,5105.0,NaN,NaN,NaN,NaN,NaN,NaN,48.218797,NaN